# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
        id.new_generator_mappings: false
  datasource:
    # In Memory
    url: jdbc:h2:mem:voting
      # tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: sa
    password:
  h2:
    console:
      enabled: true


